### ISSUE TITLE
Migration Generation throwing error

### ISSUE THREAD

**Issue by palamedes** [chrome/markable#25]
Trying to use your gem, looks great.. but I can't seem to generate the migration.  I get the following - wrong version of ruby or something?;

```
foo$ rails generate markable:migration

/Users/foo/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `attr_accessible' for #<Class:0x007fb143b20c90> (NoMethodError)
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/markable-0.1.4/lib/models/mark.rb:6:in `<class:Mark>'
from /Users/foo/.rvm/gems/ruby-2.2.2/gems/markable-0.1.4/lib/models/mark.rb:2:in `<module:Markable>'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/markable-0.1.4/lib/models/mark.rb:1:in `<top (required)>'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
from /Users/foo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
from /Users/foo/.rvm/gems/ruby-2.2.2/gems/markable-0.1.4/lib/markable.rb:2:in `<top (required)>'
        from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
        from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
        from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
        from /Users/foo/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
        from /Users/foo/Sites/GROK/GrokCasts/config/application.rb:7:in `<top (required)>'
from /Users/foo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:141:in `require'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
from /Users/foo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/foo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by palamedes** [comment]
AH!  Its this; https://github.com/chrome/markable/issues/18

Please release a new version =)
